title: bingwallpapers
description: bingwallpapers download and changer.
show_downloads: true
google_analytics:
# theme: jekyll-theme-hacker
remote-theme: jekyll-theme-chirpy
# remote-theme: piharpi/jekyll-klise
# theme: minimal-mistakes-jekyll
# remote-theme: cotes2020/jekyll-theme-chirpy
