# title: bingwallpapers
# description: bingwallpapers download and changer.
# show_downloads: true
# google_analytics:
# theme: jekyll-theme-hacker

#----------------------------------------------------------------------
# title: bingwallpapers
# # logo: /assets/img/logo.png
# description: bingwallpapers download and changer.
# show_downloads: true
# google_analytics:
# theme: jekyll-theme-minimal

#----------------------------------------------------------------------
# title: bingwallpapers
# description: "bingwallpapers download and changer."
# baseurl: "/"
# url: "https://bingwallpapaers.bkit.dev"

# header_pages:
#   - index.md

# style: dark

# footer: 'fo'

# # Build settings
# markdown: kramdown
# remote_theme: b2a3e8/jekyll-theme-console

#----------------------------------------------------------------------
# remote_theme: murraco/jekyll-theme-minimal-resume

#----------------------------------------------------------------------
#remote_theme: "mmistakes/minimal-mistakes@4.26.2"
title: bingwallpapers
email:
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
twitter_username: username
github_username: username
minimal_mistakes_skin: air # air, dark, default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "First Lastname"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "My awesome biography constrained to a sentence or two goes here."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

#----------------------------------------------------------------------
# not working remote_theme: alshedivat/al-folio
# remote_theme : mmistakes/minimal-mistakes
# not working remote_theme: cotes2020/jekyll-theme-chirpy/tree/v6.2.2

#----------------------------------------------------------------------
# partial working remote_theme: nemkin/jekyll-theme-chirpy
# title: bkit
# tagline: bkit
# description: bkit
# # avatar: /assets/img/balloons-cartoon.png

# github:
#   username: bkit

# social:
#   name: bkit
#   email: bkit
#   links:
#     - https://

# lang: en
# timezone: Asia/Seoul

#----------------------------------------------------------------------
# remote_theme: nemkin/jekyll-theme-chirpy
# theme_mode: dark

# # toc: true
# # paginate: 10
# pwa:
#   enabled: false
# future: true

# plugins:
#   - jekyll-remote-theme
#   - jekyll-paginate
#   - jekyll-redirect-from
#   - jekyll-seo-tag
#   - jekyll-archives
#   - jekyll-sitemap

# # # ------------ The following options are not recommended to be modified ------------------

# kramdown:
#   syntax_highlighter: rouge
#   syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
#     css_class: highlight
#     # default_lang: console
#     span:
#       line_numbers: false
#     block:
#       line_numbers: true
#       start_line: 1

# # collections:
# #   tabs:
# #     output: true
# #     sort_by: order

# defaults:
#   # - scope:
#   #     path: "" # An empty string here means all files in the project
#   #     type: posts
#   #   values:
#   #     layout: post
#   #     comments: true # Enable comments in posts.
#   #     toc: true # Display TOC column in posts.
#   #     # DO NOT modify the following parameter unless you are confident enough
#   #     # to update the code of all other post links in this project.
#   #     permalink: /posts/:year-:month-:day-:slug/
#   - scope:
#       path: _drafts
#     values:
#       comments: false
#   - scope:
#       path: ""
#       type: tabs # see `site.collections`
#     values:
#       layout: page
#       permalink: /:slug/
#   - scope:
#       path: assets/img/favicons
#     values:
#       swcache: true
#   - scope:
#       path: assets/js/dist
#     values:
#       swcache: true

# sass:
#   style: compressed

# compress_html:
#   clippings: all
#   comments: all
#   endings: all
#   profile: false
#   blanklines: false
#   ignore:
#     envs: [development]

# exclude:
#   - "*.gem"
#   - "*.gemspec"
#   - docs
#   - tools
#   - README.md
#   - CHANGELOG.md
#   - LICENSE
#   - rollup.config.js
#   - package*.json

# jekyll-archives:
#   enabled: [categories, tags]
#   layouts:
#     category: category
#     tag: tag
#   permalinks:
#     tag: /tags/:name/
#     category: /categories/:name/
