# title: bingwallpapers
# description: bingwallpapers download and changer.
# show_downloads: true
# google_analytics:
# theme: jekyll-theme-hacker

#----------------------------------------------------------------------
# title: bingwallpapers
# # logo: /assets/img/logo.png
# description: bingwallpapers download and changer.
# show_downloads: true
# google_analytics:
# theme: jekyll-theme-minimal

#----------------------------------------------------------------------
# title: bingwallpapers
# description: "bingwallpapers download and changer."
# baseurl: "/"
# url: "https://bingwallpapaers.bkit.dev"

# header_pages:
#   - index.md

# style: dark

# footer: 'fo'

# # Build settings
# markdown: kramdown
# remote_theme: b2a3e8/jekyll-theme-console

#----------------------------------------------------------------------
# remote_theme: murraco/jekyll-theme-minimal-resume

#----------------------------------------------------------------------
#remote_theme: "mmistakes/minimal-mistakes@4.26.2"
title: bingwallpapers
email:
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
twitter_username: username
github_username: username
minimal_mistakes_skin: dark # air, dark, neon, default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "First Lastname"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "My awesome biography constrained to a sentence or two goes here."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

#----------------------------------------------------------------------
# not working remote_theme: alshedivat/al-folio
# not working remote_theme: cotes2020/jekyll-theme-chirpy/tree/v6.2.2

#----------------------------------------------------------------------
# partial working 
# remote_theme: nemkin/jekyll-theme-chirpy
# title: bkit
# tagline: bkit
# description: bkit
# # avatar: /assets/img/balloons-cartoon.png

# github:
#   username: bkit

# social:
#   name: bkit
#   email: bkit
#   links:
#     - https://

# lang: en
# timezone: Asia/Seoul

