# title: bingwallpapers
# description: bingwallpapers download and changer.
# show_downloads: true
# google_analytics:
# theme: jekyll-theme-hacker

# remote_theme: nemkin/jekyll-theme-chirpy
# remote_theme: cotes2020/jekyll-theme-chirpy/tree/v6.2.2

remote_theme: mmistakes/minimal-mistakes
# remote-theme: piharpi/jekyll-klise
